import enumimport routing
class FootprintKeyMaskBits(enum.IntFlags):
    SMALL_HEIGHT = routing.FOOTPRINT_KEY_REQUIRE_SMALL_HEIGHT
    TINY_HEIGHT = routing.FOOTPRINT_KEY_REQUIRE_TINY_HEIGHT
    LOW_HEIGHT = routing.FOOTPRINT_KEY_REQUIRE_LOW_HEIGHT
    MEDIUM_HEIGHT = routing.FOOTPRINT_KEY_REQUIRE_MEDIUM_HEIGHT
    FLOATING = routing.FOOTPRINT_KEY_REQUIRE_FLOATING
    LARGE_HEIGHT = routing.FOOTPRINT_KEY_REQUIRE_LARGE_HEIGHT
